### ISSUE TITLE
Porting to ROS2

### ISSUE THREAD

**Issue by ymd-stella** [stella-cv/theta_driver#1]

**Comment by JLBicho** [comment]
Hi!
Thanks for creating this repo!
I'm starting the port to ROS2-Foxy. Maybe I'll need some support, I'll contact you if needed. :) 
https://github.com/JLBicho/theta_driver/tree/ros2_foxy

**Comment by JLBicho** [comment]
Hi again!
I'm a little stuck in my branch. Maybe you can provide some help.
I've updated the source code and the CMakeList for ROS2-Foxy, but I'm not able to finalize the compilation steps. The linker cannot find the uvc functions.
Do you have any idea of what could be going wrong here?
Thanks!
https://github.com/JLBicho/theta_driver/issues/1

**Comment by ymd-stella** [comment]
I think the content of ament_target_dependencies is wrong.
https://github.com/JLBicho/theta_driver/blob/f6f308b349820d91b1447452a4b4db3f17a78d0a/CMakeLists.txt#L55-L59

**Comment by JLBicho** [comment]
Hi! Thanks for the feedback. I also think there is something wrong there but I cannot figure out what. If I put the same elements as in catkin, I get the following during compilation:

`Starting >>> theta_driver
--- stderr: theta_driver                         
CMake Error at /opt/ros/foxy/share/ament_cmake_target_dependencies/cmake/ament_target_dependencies.cmake:77 (message):
  ament_target_dependencies() the passed package name 'gstreamer-1.0' was not
  found before
Call Stack (most recent call first):
  CMakeLists.txt:53 (ament_target_dependencies)


make:  *** [Makefile:340: cmake_check_build_system] Error 1
---
Failed   <<< theta_driver [0.56s, exited with code 2]

Summary: 0 packages finished [0.63s]
  1 package failed: theta_driver
  1 package had stderr output: theta_driver
`

And the same with each element: Boost, OpenCV, gstreamer, etc... 
However, with the names I have written, everything except the uvc works. I've done some "testing" changing OpenCV to "opencv" and it says this:

`Starting >>> theta_driver
--- stderr: theta_driver                         
CMake Error at /opt/ros/foxy/share/ament_cmake_target_dependencies/cmake/ament_target_dependencies.cmake:77 (message):
  ament_target_dependencies() the passed package name '**opencv**' was not found
  before
Call Stack (most recent call first):
  CMakeLists.txt:53 (ament_target_dependencies)


make: *** [Makefile:340: cmake_check_build_system] Error 1
---
Failed   <<< theta_driver [0.53s, exited with code 2]

Summary: 0 packages finished [0.60s]
  1 package failed: theta_driver
  1 package had stderr output: theta_driver
`
So I assume that it finds OpenCV but not **opencv**. Same thing happens with the other elements, if I change one letter for example, it says it cannot find it, but with the correct name there is no error.

Additionally, if I don't put the GSTREAMER_1_0 and GSTREAMER_1_0_APP, the error message is:

`Starting >>> theta_driver
--- stderr: theta_driver                             
/usr/bin/ld: CMakeFiles/theta_driver_node.dir/3rd/libuvc-theta-sample/gst/thetauvc.c.o: in function `thetauvc_find_devices':
thetauvc.c:(.text+0x3f): undefined reference to `uvc_find_devices'
/usr/bin/ld: thetauvc.c:(.text+0x76): undefined reference to `uvc_free_device_list'
/usr/bin/ld: thetauvc.c:(.text+0xb1): undefined reference to `uvc_get_device_descriptor'
/usr/bin/ld: thetauvc.c:(.text+0x118): undefined reference to `uvc_free_device_list'
/usr/bin/ld: thetauvc.c:(.text+0x124): undefined reference to `uvc_free_device_descriptor'
/usr/bin/ld: thetauvc.c:(.text+0x184): undefined reference to `uvc_free_device_descriptor'
/usr/bin/ld: thetauvc.c:(.text+0x1d6): undefined reference to `uvc_ref_device'
/usr/bin/ld: thetauvc.c:(.text+0x1f3): undefined reference to `uvc_free_device_list'
/usr/bin/ld: CMakeFiles/theta_driver_node.dir/3rd/libuvc-theta-sample/gst/thetauvc.c.o: in function `thetauvc_print_devices':
thetauvc.c:(.text+0x29a): undefined reference to `uvc_perror'
/usr/bin/ld: thetauvc.c:(.text+0x2f4): undefined reference to `uvc_get_device_descriptor'
/usr/bin/ld: thetauvc.c:(.text+0x332): undefined reference to `uvc_free_device_descriptor'
/usr/bin/ld: thetauvc.c:(.text+0x367): undefined reference to `uvc_free_device_list'
/usr/bin/ld: CMakeFiles/theta_driver_node.dir/3rd/libuvc-theta-sample/gst/thetauvc.c.o: in function `thetauvc_find_device':
thetauvc.c:(.text+0x3fc): undefined reference to `uvc_free_device_list'
/usr/bin/ld: thetauvc.c:(.text+0x428): undefined reference to `uvc_ref_device'
/usr/bin/ld: thetauvc.c:(.text+0x451): undefined reference to `uvc_free_device_list'
/usr/bin/ld: CMakeFiles/theta_driver_node.dir/3rd/libuvc-theta-sample/gst/thetauvc.c.o: in function `thetauvc_find_device_by_serial':
thetauvc.c:(.text+0x523): undefined reference to `uvc_get_device_descriptor'
/usr/bin/ld: thetauvc.c:(.text+0x562): undefined reference to `uvc_free_device_descriptor'
/usr/bin/ld: thetauvc.c:(.text+0x582): undefined reference to `uvc_ref_device'
/usr/bin/ld: thetauvc.c:(.text+0x59e): undefined reference to `uvc_free_device_list'
/usr/bin/ld: CMakeFiles/theta_driver_node.dir/3rd/libuvc-theta-sample/gst/thetauvc.c.o: in function `thetauvc_get_stream_ctrl_format_size':
thetauvc.c:(.text+0x62b): undefined reference to `uvc_get_stream_ctrl_format_size'
/usr/bin/ld: CMakeFiles/theta_driver_node.dir/3rd/libuvc-theta-sample/gst/thetauvc.c.o: in function `thetauvc_run_streaming':
thetauvc.c:(.text+0x674): undefined reference to `uvc_open'
/usr/bin/ld: thetauvc.c:(.text+0x6d2): undefined reference to `uvc_start_streaming'
/usr/bin/ld: thetauvc.c:(.text+0x6e4): undefined reference to `uvc_close'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_buffer_copy_deep'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_app_src_set_caps'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_buffer_map'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_pipeline_set_clock'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `uvc_init'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `g_error_free'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_pipeline_get_bus'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_object_unref'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_pipeline_get_type'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_element_set_state'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `g_type_check_instance_cast'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_buffer_unmap'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `g_main_loop_quit'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `uvc_exit'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_sample_get_buffer'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `g_main_loop_new'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `g_signal_connect_data'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_bin_get_by_name'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_caps_new_simple'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_system_clock_obtain'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `uvc_stop_streaming'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_parse_launch'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `g_free'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_bin_get_type'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_buffer_new_allocate'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_mini_object_unref'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_message_parse_error'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_init'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `g_print'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `_gst_fraction_type'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `g_timer_new'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_bus_add_watch'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_is_initialized'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `g_signal_emit_by_name'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_app_src_get_type'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `gst_app_sink_pull_sample'
/usr/bin/ld: libtheta_driver_lib.so: undefined reference to `g_source_remove'
`
As you can see, the **gst** functions are also not found. So when my understanding is that when I write GSTREAMER_1_0 and GSTREAMER_1_0_APP in the dependencies, it is able to find the **gst** functions.

I think that libuvc is correctly installed because the libuvc-theta-sample works perfect, so i believe it has something to do with the linker.

I hope something of this big comment can help you help me :) I appreciate greatly your support.

**Comment by JLBicho** [comment]
Good news! I made it work :smile: 
We need first to check the libuvc module:
https://github.com/JLBicho/theta_driver/blob/7c12edb625f29f63ec0b15fa77e6cfc414939fed/CMakeLists.txt#L32

Then put it in the dependencies like this
https://github.com/JLBicho/theta_driver/blob/7c12edb625f29f63ec0b15fa77e6cfc414939fed/CMakeLists.txt#L59

And now it works:
![image](https://user-images.githubusercontent.com/12575739/168977242-0c2725a5-2dbe-40ef-95d6-fe446f3bd593.png)

![image](https://user-images.githubusercontent.com/12575739/168977347-a23c1d81-2531-4950-9089-5bf72a4ab636.png)

**Comment by Lee-JaeWon** [comment]
@ymd-stella 
@JLBicho 

Thank you for your work.
I'm trying to get my ricoh theta z1 working with ros2 foxy by following the readme on github, but it won't **streaming** after the following statement.

```
[INFO] [1712757387.217201940] [theta_driver]: Initializing
[INFO] [1712757387.236832637] [theta_driver]: index: 0
[INFO] [1712757387.236859398] [theta_driver]: product: RICOH THETA Z1
[INFO] [1712757387.236864787] [theta_driver]: serial: 32101106
```
I think I've satisfied all the dependencies, so what's the problem?

**Comment by Lee-JaeWon** [comment]
@JLBicho @JLBicho 
The same is true if i change the streaming variable to true in your code.
The RICOH THETA Z1 is also set to LIVE MODE.

**Comment by Lee-JaeWon** [comment]
@JLBicho @ymd-stella 
The same is true if i change the `streaming` variable to true in your code.
The RICOH THETA Z1 is also set to LIVE MODE.

I checked and it looks like the code doesn't go past the bottom part.

```
if (use4k_) {
          thetauvc_get_stream_ctrl_format_size(devh_, THETAUVC_MODE_UHD_2997, &ctrl_);
      }
      else {
          thetauvc_get_stream_ctrl_format_size(devh_, THETAUVC_MODE_FHD_2997, &ctrl_);
      }
```

**Comment by JLBicho** [comment]
Hi @Lee-JaeWon,

I actually can't help you a lot because the only thing I did was changing ROS 1 functions to ROS 2.

However, I can suggest the following steps.

1. Check the USB cable. To stream the video you need USB 3.0 cable, at least.
2. Check QoS. Set in Rviz2 the QoS to Best effort.
3. Check with `ros2 topic echo` if the message is being published.

It's been a long time since I've worked with this camera and maybe some packages have been updated and they don't work anymore.

Please, when you launch the camera again send a screenshot of the output of `ros2 topic list` and check it the camera screen says anything more about the streaming.

I hope this helps.

**Comment by Lee-JaeWon** [comment]
@JLBicho 
Thank you so much for your response.

The problem is that the node that I run in the terminal before checking with rviz2 or topic is turned off immediately after turning on.

Do you have any experience with this?

**Comment by JLBicho** [comment]
This may be a segmentation fault or something similar.

Please, run the node in debug mode adding `--ros-args --log-level debug` at the end of the command and paste the output here.

Additionally, make sure all your packages are updated and upgraded with
`sudo apt update && sudo apt upgrade -y`
